import type { Metadata } from "next";
import { Pathway_Extreme } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import ProgressBarProvider from "@/utils/progressBar";
import ReactQueryProvider from "@/utils/reactQueryProvider";

const pathway_extreme = Pathway_Extreme({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MOVIEFLIX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={`${pathway_extreme.className} bg-zinc-900`}>
          <ReactQueryProvider>
            {children}
            <ProgressBarProvider />
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
